Auto-tag releases via svn-push script

diff --git a/bin/svn-push b/bin/svn-push
--- a/bin/svn-push
+++ b/bin/svn-push
@@ -1,4 +1,7 @@
 #!/bin/bash
+# Given a svn-url file one directory up, export the latest git commits to the specified SVN repo.
+# Create a git release tag from the verison specified in the plugin file.
+# Author: Weston Ruter (@westonruter)
 
 set -e
 
@@ -20,10 +23,31 @@ current_branch=$(git rev-parse --abbrev-ref HEAD)
 if [ $current_branch != 'master' ]; then
 	git checkout master
 fi
+
 git pull origin master
 git push origin master
 svn_url=$(cat svn-url)
 svn_repo_dir=$git_root/svn
+
+for php in *.php; do
+	if grep -q 'Plugin Name:' $php && grep -q 'Version:' $php; then
+		plugin_version=$(cat $php | grep 'Version:' | sed 's/.*Version: *//')
+	fi
+done
+
+if [ -z "$plugin_version" ]; then
+	echo "Unable to find plugin version"
+	exit 1
+fi
+
+if git show-ref --tags --quiet --verify -- "refs/tags/$plugin_version"; then
+	echo "Plugin version $plugin_version already tagged. Please bump version and try again"
+	exit 1
+fi
+
+echo "Tagging plugin version $plugin_version"
+git tag $plugin_version master
+git push origin $plugin_version
 
 if [ ! -e $svn_repo_dir ]; then
 	svn checkout $svn_url $svn_repo_dir
